os: linux
language: node_js

node_js:
  - lts/*

# upgrade pyenv
before_install:
  - cd $(pyenv root)
  - git pull origin master
  - cd -

install:
  - pyenv install 3.8.6
  - pyenv global 3.8.6
  - pip install pipenv
  - pipenv install
  - npm install

jobs:
  include:
    - stage: "deploy"
      script:
        - pipenv run python sprite.py
        - npm run build
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
              branch: main
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          committer_from_gh: true
          verbose: true
          project_name: mui-phone-textfield
          on:
              branch: main
