os: linux
language: node_js

node_js:
  - lts/*

addons:
  apt:
    packages:
    - python3

install:
  - python3 -m pip install pipenv
  - pipenv install
  - npm install

jobs:
  include:
    - stage: "deploy"
      script: python sprite.py && npm run build
      deploy:
        - provider: script
          cleanup: false
          script: npx semantic-release
        - provider: pages
          cleanup: false
          token: $GITHUB_TOKEN
          keep_history: true
          committer_from_gh: true
          verbose: true
          project_name: mui-phone-textfield
