name: build

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run build:dist
      - run: npx semantic-release
  gh-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "gh-pages"
      cancel-in-progress: true
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/configure-pages@v3
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./examples/public
      - uses: actions/deploy-pages@v2
